### PR TITLE
Use updated jade-inheritance and mocha

### PR DESCRIPTION
**Pull request by bfred-it**
https://github.com/paulyoung/jade-inheritance/pull/10

### CODE REVIEW

**Comment by bfred-it** [comment]
This last commit fixes the issue with the tests. For reasons I don't understand, the test runs against mocha's own jade files, which weren't valid (deprecated use of doctype), but they are fixed in 2.2.1

This can be pulled now

**Comment by juanfran** [comment]
thanks!

**Comment by bfred-it** [comment]
Thank you! Can you publish it to npm?

**Comment by juanfran** [comment]
done :smile:

**Pull request merged**
